name: Destroy GCP VM

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Destroy
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "${GOOGLE_CREDENTIALS}" > credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS="credentials.json"
          terraform init
          terraform destroy -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=us-central1" \
            -var="zone=us-central1-a"
